version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./:/var/www/html:delegated
  mysql:
    image: mysql
    volumes:
        - ./docker/provision/mysql/init:/docker-initdb.d
    env_file:
      - ./env/mysql.env
    ports:
      - '3306:3306'
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - .:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
  npm:
    image: node:latest
    working_dir: /var/www/html
    entrypoint: ['npm']
    profiles: ["npm"]
    ports:
      - '5173:5173'
    volumes:
      - ./:/var/www/html
